name: 'PHP and Twig CS check'
description: 'PHP and Twig Code sniffer check with custom ruleset'
inputs:
  phpcs_paths:
    description: 'Paths to check'
    required: false
    default: './modules'
  twigcs_paths:
    description: 'Paths to check'
    required: false
    default: './templates'
  enable_warnings:
    description: 'Enable checking for warnings (-w)'
    required: false
    default: 'true'
  phpcs_bin_path:
    description: 'Path to phpcs binary'
    required: false
    default: 'phpcs'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.phpcs_paths }}
    - ${{ inputs.twigcs_paths }}
