name: 'PHP CS check'
description: 'PHP Code sniffer check with custom ruleset'
inputs:
  phpcs_paths:
    description: 'Paths to check'
    required: false
    default: './modules'
  enable_warnings:
    description: 'Enable checking for warnings (-w)'
    required: false
    default: 'true'
  phpcs_bin_path:
    description: 'Path to phpcs binary'
    required: false
    default: 'phpcs'
  phpcs_ignore_paths:
    description: 'Paths to ignore'
    required: false
    default: '*/tests/*,*/data/*,*/libraries/*'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.phpcs_paths }}
